deck36_storm:
    HighFiveBolt:
        main:       "storm:bolt:HighFive"
        params:
        rabbitmq:
            exchange:        "plan9"
            routing_key:     "cbt.#"
            target_exchange: "plan9-backchannel"
        badge_timewindow:   35
        badge:
            name: "HighFive"
            text: "Hands up! You used the same cat to solve! Hooray!"
            color:   "red"
            size:    "2em"
            effect:  "explode"

    EmptyTickTupleBolt:
        main:       "storm:bolt:EmptyTickTuple"
        params:
        rabbitmq:
            exchange:        "plan9"
            routing_key:     "#"
            target_exchange: "plan9-backchannel"
        tick_frequency:     10
        badge:
            name: "EmptyTickTuple"
            text: "Something just happened, that didn't just happen."
            color:   "red"
            size:    "2em"
            effect:  "explode"

    DeludedKittenRobbersBolt:
        main:       "storm:bolt:DeludedKittenRobbers"
        params:
        rabbitmq:
            exchange:        "plan9"
            routing_key:     "#"
            target_exchange: "plan9-backchannel"
        attack_frequency_secs:  10        
        badge:
            name: "DeludedKittenRobbers"
            text: "The deluded Kitten Robbers came from Outer Space to punish you for exhilarating too many too young kittens."
            color:   "red"
            size:    "2em"
            effect:  "explode"


    KittenRobbersFromOuterSpaceBolt:
        main:       "storm:bolt:KittenRobbers"
        params:
        rabbitmq:
            exchange:        "plan9"
            routing_key:     "cbt.#"
            target_exchange: "plan9-backchannel"
        robber_frequency:    2
        badge:
            name:   "KittenRobbersFromOuterSpace"
            text:   "The mysterious Kitten Robbers came from Outer Space and took your cat away! Oh no!!!!1"
            color:   "red"
            size:    "2em"
            effect:  "puff"



    RecordBreakerBolt:
        main:       "storm:bolt:RecordBreaker"
        params:
        rabbitmq:
            exchange:        "plan9"
            routing_key:     "#"
            target_exchange: "plan9-backchannel"
        badge:
            name:   "RecordBreaker"
            text:   "You broke your own record! Woo hoo!"
            color:   "red"
            size:    "2em"
            effect:  "drop"


    RecordMasterBolt:
        main:       "storm:bolt:RecordMaster"
        params:
        badge:
            name:   "RecordMaster"
            text:   "Mastered! You're the No. 1 Record Breaker! w00000t!"
            color:   "red"
            size:    "2em"
            effect:  "explode"



    StatusLevelBolt:
        main:       "storm:bolt:StatusLevel"
        params:
        rabbitmq:
            exchange:        "plan9"
            routing_key:     "points.#"
            target_exchange: "plan9-backchannel"
        levels:
            "Hatched Kitty":        0
            "Player Kitty":         1
            "Tweety Kitty":         2
            "Lonely Kitty":         3
            "Greedy Kitty":         4
            "Cat Kong":             5
            "Needy Kitty":          6
            "Meaty Kitty":          7
            "Die Grinsekatze":      8
            "Halo Kitty":           9
            "Cat Mandu":            10
            "Hundred Kitties":      11
            "Pinky Kitty": 150
            "Chester Cat": 202
            "Hodge Podge": 242
            "Grumpy Cat": 303
            "Daisy Kitty": 355
            "Troll Cat": 397
            "Kitty Doll": 461
            "Lazy Kitty": 485
            "Cap Cat Cartoon": 503
            "Pogo Kitty": 580
            "Der gestiefelte Kater": 633
            "Pony Kitty": 655
            "Cat Balance": 687
            "Juggler Cat": 704
            "Kitty Mouse Mouse": 832
            "Cat Poem": 999
            "Onyx Cat": 1023
            "Bully Cat": 1042
            "Catroller": 1088
            "Markovian Cat": 1111
            "Missy Kitty Cat": 1289
            "Sponsored Cat": 1421
            "Kitty LaChatte": 1511
            "Colonel Meow": 1590
            "Uncle Cat": 1670
            "Big ": 1733
            "Hamilton, the Hipster Cat": 1833
            "Donkey Kitty": 1967
            "Vampyra Cat": 2001
            "Slayer Cat": 2121
            "Tomcat": 2222
            "Cat Commander": 2685
            "Bela Lugosi": 8305
            "Bhagwahn Guru Guru Guru": 17231
            "Vampire Alien Overlord": 28920
            "Ed Wood": 43216
        badge:
            name:   "StatusLevel"
            text:   "You achieved a new level! Welcome!"
            color:   "red"
            size:    "2em"
            effect:  "explode"

    WheelOfKittenBolt:
            main:       "storm:bolt:WheelOfKitten"
            params:
            rabbitmq:
                exchange:        "plan9"
                routing_key:     "points.#"
                target_exchange: "plan9-backchannel"
            badge:
                name:   "WheelOfKitten"
                text:   "YES ran the wheel."
                color:   "red"
                size:    "2em"
                effect:  "explode"


    PrimeCatBolt:
        main:       "storm:bolt:PrimeCat"
        params:
        rabbitmq:
            exchange:        "plan9"
            routing_key:     "points.#"
            target_exchange: "plan9-backchannel"
        primecat_frequency:  10
        badge_timewindow:    60
        badge:
            name:   "PrimeCat"
            text:   "You made more points in the recent past than any other player! You're so prime!"
            color:   "red"
            size:    "2em"
            effect:  "puff"


    StumbleBlunderBolt:
        main:       "storm:bolt:StumbleBlunder"
        params:
        rabbitmq:
            exchange:        "plan9"
            routing_key:     "cbt.#"
            target_exchange: "plan9-backchannel"
        badge_timewindow:   180
        max_tolerance:      5
        badge:
            name:   "StumbleBlunder"
            text:   "So many errors in a row! Oh no! Gotta teach you somethin'! You must earn the priviledge to gain points again!"
            color:   "red"
            size:    "2em"
            effect:  "explode"



    RaiderOfTheKittenRobbersBolt:
        main:       "storm:bolt:RaiderOfTheKittenRobbers"
        params:
        rabbitmq:
            target_exchange: "plan9-backchannel"
        badge_timewindow:           60
        the_chosen_one_timewindow:  115
        badge:
            name:   "RaiderOfTheKittenRobbers"
            text:   "Your HighFive taught the Kitten Robbers a lesson! You're now the Chosen One!"
            color:   "red"
            size:    "2em"
            effect:  "explode"



